apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanagement-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanagement-backend
  template:
    metadata:
      labels:
        app: taskmanagement-backend
    spec:
      containers:
        - name: backend
          image: taskmanagement-backend:1.0   # your built backend image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/task_management"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: taskmanagement-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
