apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanagement-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanagement-frontend
  template:
    metadata:
      labels:
        app: taskmanagement-frontend
    spec:
      containers:
        - name: task-frontend
          image: taskmanagement-frontend:latest   # FIXED NAME
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: taskmanagement-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
